import type { LoveNote } from "./types";

export const loveNotes: LoveNote[] = [
  {
    id: 1,
    message: "I miss you.",
    emoji: "💌",
    variant: "glass",
    rotation: -6,
    floatDuration: 8,
    delay: 0,
  },
  {
    id: 2,
    message: "You're my safest place.",
    emoji: "❤️",
    variant: "rose",
    rotation: 5,
    floatDuration: 10,
    delay: 1,
  },
  {
    id: 3,
    message: "I'll always choose you.",
    emoji: "🌹",
    variant: "midnight",
    rotation: -4,
    floatDuration: 9,
    delay: 2,
  },
  {
    id: 4,
    message: "I believe in us.",
    emoji: "✨",
    variant: "glass",
    rotation: 7,
    floatDuration: 11,
    delay: 0.5,
  },
  {
    id: 5,
    message: "Home is wherever you are.",
    emoji: "🏡",
    variant: "rose",
    rotation: -8,
    floatDuration: 8,
    delay: 1.5,
  },
  {
    id: 6,
    message: "Thank you for staying.",
    emoji: "🤍",
    variant: "midnight",
    rotation: 4,
    floatDuration: 12,
    delay: 2.5,
  },
  {
    id: 7,
    message: "Every call makes my day.",
    emoji: "📞",
    variant: "glass",
    rotation: -3,
    floatDuration: 9,
    delay: 0.8,
  },
  {
    id: 8,
    message: "Distance can't change us.",
    emoji: "🌍",
    variant: "rose",
    rotation: 6,
    floatDuration: 10,
    delay: 1.8,
  },
  {
    id: 9,
    message: "Forever starts with us.",
    emoji: "♾️",
    variant: "midnight",
    rotation: -5,
    floatDuration: 11,
    delay: 2.2,
  },
  {
    id: 10,
    message: "You're my favorite hello.",
    emoji: "😊",
    variant: "glass",
    rotation: 8,
    floatDuration: 8,
    delay: 1,
  },
  {
    id: 11,
    message: "Every goodbye brings us closer.",
    emoji: "🥹",
    variant: "rose",
    rotation: -7,
    floatDuration: 12,
    delay: 0.3,
  },
  {
    id: 12,
    message: "You're my peace.",
    emoji: "🕊️",
    variant: "midnight",
    rotation: 5,
    floatDuration: 9,
    delay: 2,
  },
  {
    id: 13,
    message: "Every memory is precious.",
    emoji: "📸",
    variant: "glass",
    rotation: -2,
    floatDuration: 10,
    delay: 1.3,
  },
  {
    id: 14,
    message: "You make ordinary days special.",
    emoji: "☀️",
    variant: "rose",
    rotation: 3,
    floatDuration: 11,
    delay: 2.8,
  },
  {
    id: 15,
    message: "My favorite future includes you.",
    emoji: "💖",
    variant: "midnight",
    rotation: -6,
    floatDuration: 10,
    delay: 1.7,
  },
];